MASTER_KEY_PAIR_PATH = Rails.root.join("master_key_pair")
PRIVATE_KEY_PATH =  Rails.root.join("master_key_pair","private.key")
PUBLIC_KEY_PATH = Rails.root.join("master_key_pair","public.key")
TEMP_PASSPHRASE_FILE_PATH = Rails.root.join("/tmp/tmpPassphrase")
TEMP_OLD_PASSPHRASE_FILE_PATH = Rails.root.join("/tmp/tmpOldPassphrase")
