production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  database: oav_production
  pool: 5
  host: localhost
  port: 3306
  username: root
  password:

development: 
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  database: oav_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  database: oav_test
  pool: 5
  username: root 
  password:
